### ISSUE TITLE
[Feature Request] Display user-friendly error messages

### ISSUE THREAD

**Issue by jcpineda15** [m-inamori/Graphite#4]
It would be helpful to the user if the error messages displayed by the system is understandable (not technical)

For example, consider the following scenarios:

1. Bad Pedigree file structure -  1 row has less than 4 columns
    - Displayed error message (current): "Assertion failed: (v.size() >= 4U), function create, file Pedigree.cpp, line 43
    - Displayed error message (suggested): Pedigree file format error. Each row should have at least 4 columns
    - Test files: [Rice_all_genotype.vcf.gz](https://github.com/m-inamori/Graphite/files/15258435/Rice_all_genotype.vcf.gz), [Rice_ped_23samples_1 row less than 4 columns.txt](https://github.com/m-inamori/Graphite/files/15258556/Rice_ped_23samples_1.row.less.than.4.columns.txt)
2. VCF file samples not matching with samples in pedigree file
    - Displayed error message (current): zsh: floating point exception
    - Displayed error message (suggested): VCF file samples do not match with samples in the pedigree file. 
    - Test files: [mdp_genotype.vcf.gz](https://github.com/m-inamori/Graphite/files/15258563/mdp_genotype.vcf.gz),  [Rice_ped_23samples.txt](https://github.com/m-inamori/Graphite/files/15258566/Rice_ped_23samples.txt)

3. Bad VCF file structure - incomplete metadata
    - Displayed error message (current): zsh: segmentation fault
    - Displayed error message (suggested): VCF file format error. Please check your file and make sure it follows the standard.
    - Test files: [Rice_all_genotype_incomplete-header_segmentation-fault.vcf.gz](https://github.com/m-inamori/Graphite/files/15259017/Rice_all_genotype_incomplete-header_segmentation-fault.vcf.gz), [Rice_ped_23samples.txt](https://github.com/m-inamori/Graphite/files/15259018/Rice_ped_23samples.txt)

**Comment by jcpineda15** [comment]
added scenario 3: Bad VCF file structure - incomplete metadata

**Comment by m-inamori** [comment]
I have fixed them.
